name: build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-2019
    steps:
    - name: Check out git repository
      uses: actions/checkout@v2
    - name: Set up MSVC Developer Command Prompt
      uses: seanmiddleditch/gha-setup-vsdevenv@v3
    - name: Install dependencies and build
      run: .\build_with_vcpkg.bat
